allowBuilds:
  '@shopify/react-native-skia': true
  esbuild: true
  sharp: true

nodeLinker: hoisted

patchedDependencies:
  react-native-element-dropdown: patches/react-native-element-dropdown.patch
  react-native-image-viewing: patches/react-native-image-viewing.patch
