allowBuilds:
  '@shopify/react-native-skia': true
  esbuild: true
  postinstall-postinstall: true
  sharp: true

nodeLinker: hoisted

patchedDependencies:
  react-native-notify-kit: patches/react-native-notify-kit.patch
