allowBuilds:
  '@shopify/react-native-skia': true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - react-native-notify-kit@10.4.4

nodeLinker: hoisted

patchedDependencies:
  react-native-element-dropdown: patches/react-native-element-dropdown.patch
  react-native-image-viewing: patches/react-native-image-viewing.patch
